mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from plants.views import plantlist,plant1,plant2,plant3,plant4,plant5,plant6,plant7,plant8,plant9,plant10,plant11,plant12,plant13,plant14,plant15
from homepage.views import home,link,photo,introduce,newbie
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^plantlist/$', plantlist),
    url(r'^homepage/$', home),
    url(r'^link/$', link),    
    url(r'^introduce/$', introduce),
    url(r'^newbie/$', newbie),
    url(r'^photo/$', photo),
    url(r'^七福神圖鑑詳細資料/$', plant1),
    url(r'^月兔耳圖鑑詳細資料/$', plant2),
    url(r'^玉露圖鑑詳細資料/$', plant3),
    url(r'^生石花圖鑑詳細資料/$', plant4),
    url(r'^白鳳菊圖鑑詳細資料/$', plant5),
    url(r'^星兜圖鑑詳細資料/$', plant6),
    url(r'^虹之玉圖鑑詳細資料/$', plant7),
    url(r'^姬星美人圖鑑詳細資料/$', plant8),
    url(r'^球松圖鑑詳細資料/$', plant9),
    url(r'^雪蓮圖鑑詳細資料/$', plant10),
    url(r'^熊童子圖鑑詳細資料/$', plant11),
    url(r'^碧光環圖鑑詳細資料/$', plant12),
    url(r'^錦上珠圖鑑詳細資料/$', plant13),
    url(r'^露娜蓮圖鑑詳細資料/$', plant14),
    url(r'^鷹爪圖鑑詳細資料/$', plant15),
    
)


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)






    

homepage/models.py
from django.db import models

# Create your models here.

plants/models.py
from django.db import models

# Create your models here.
class  Plantkind(models.Model):
	name = models.CharField(max_length=20)	
	introduce = models.CharField(max_length=50, blank=True)

	def __str__(self):
		return self.name

class  Plant(models.Model):
	name = models.CharField(max_length=20)			
	plantkind = models.ForeignKey(Plantkind)
	
	def __str__(self):
		return self.name

homepage/views.py
from django.shortcuts import render_to_response

# Create your views here.
# -*-coding: uth-8 -*-
def home(request):
	return render_to_response('homepage.html',locals())

def link(request):
	return render_to_response('link.html',locals())

def photo(request):
	return render_to_response('photo.html',locals())

def introduce(request):
	return render_to_response('introduce.html',locals())

def newbie(request):
	return render_to_response('newbie.html',locals())

plants/views.py
from django.shortcuts import render_to_response
from plants.models import Plantkind, Plant
# Create your views here.
# -*-coding: uth-8 -*-
def plantlist(request):
	plants = Plant.objects.all()
	kinds = Plantkind.objects.all()

	return render_to_response('plant.html',locals())


def plant1(request):

	return render_to_response('七福神圖鑑詳細資料.html',locals())

def plant2(request):

	return render_to_response('月兔耳圖鑑詳細資料.html',locals())

def plant3(request):

	return render_to_response('玉露圖鑑詳細資料.html',locals())

def plant4(request):

	return render_to_response('生石花圖鑑詳細資料.html',locals())

def plant5(request):

	return render_to_response('白鳳菊圖鑑詳細資料.html',locals())

def plant6(request):

	return render_to_response('星兜圖鑑詳細資料.html',locals())

def plant7(request):

	return render_to_response('虹之玉圖鑑詳細資料.html',locals())

def plant8(request):

	return render_to_response('姬星美人圖鑑詳細資料.html',locals())

def plant9(request):

	return render_to_response('球松圖鑑詳細資料.html',locals())

def plant10(request):

	return render_to_response('雪蓮圖鑑詳細資料.html',locals())

def plant11(request):

	return render_to_response('碧光環圖鑑詳細資料.html',locals())

def plant12(request):

	return render_to_response('月兔耳圖鑑詳細資料.html',locals())

def plant13(request):

	return render_to_response('錦上珠圖鑑詳細資料.html',locals())

def plant14(request):

	return render_to_response('露娜蓮圖鑑詳細資料.html',locals())

def plant15(request):

	return render_to_response('鷹爪圖鑑詳細資料.html',locals())

homepage/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>Home Page</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<style>
	  	body {
		    background-image: url("/static/image/background.jpg");    
		    background-size: cover;
		}
		img {
		    max-width: 100%;
		    height: auto;

		}
		ul#menu {
		    padding: 0;
		    content: 100;

		}
		#footer {

		    color:white;
		    clear:both;
		    text-align:center;
		    padding:30px;	 	 
		}

		.slider_container div {
		    position: absolute;
		    top: 0;
		    left: 0;
		    right: 0;
		    opacity: 0;
		    filter: alpha(opacity=0);
		}

		.slider_container div {
		    -webkit-animation: round 25s linear infinite;
		            animation: round 25s linear infinite;
		}

		@-webkit-keyframes round {
		    4% {
		        opacity: 1;
		        filter: alpha(opacity=100);
		        /* 0 - 1秒 淡入*/
		    }
		    20% {
		        opacity: 1;
		        filter: alpha(opacity=100);
		        /* 1- 5秒靜止*/
		    }
		    24% {
		        opacity: 0;
		        filter: alpha(opacity=0);
		        /* 5-6秒淡出*/
		    }
		}
		@keyframes round {
		    4% {
		        opacity: 1;
		        filter: alpha(opacity=100);
		        /* 0 - 1秒 淡入*/
		    }
		    20% {
		        opacity: 1;
		        filter: alpha(opacity=100);
		        /* 1- 5秒靜止*/
		    }
		    24% {
		        opacity: 0;
		        filter: alpha(opacity=0);
		        /* 5-6秒淡出*/
		    }
		}

		.slider_container div:nth-child(5) {
		    -webkit-animation-delay: 0s;
		            animation-delay: 0s;
		}

		.slider_container div:nth-child(4) {
		    -webkit-animation-delay: 5s;
		            animation-delay: 5s;
		}

		.slider_container div:nth-child(3) {
		    -webkit-animation-delay: 10s;
		            animation-delay: 10s;
		}

		.slider_container div:nth-child(2) {
		    -webkit-animation-delay: 15s;
		            animation-delay: 15s;
		}

		.slider_container div:nth-child(1) {
		    -webkit-animation-delay: 20s;
		            animation-delay: 20s;
		}

	</style>
</head>
<body>

<div class="container"> 
  
  <div class="row">
    <div class="col-sm-7">
      <img src="/static/image/homepage/TITLE.png"  width="800" height="300"><br>

  	    <ul id="menu">	
  	    	<table style="width:100%">
					
	  	    	<!-- Add "border:0;" to prevent IE9 (and earlier) from displaying a border around the image. -->
				<tr><a href="introduce.html">
				  <img src="/static/image/icon/ICON1.png" width="230px" height="80px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.0" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.0" >  <br>
				</a></tr>
				<div><a href="newbie.html">
					<img src="/static/image/icon/ICON2.png" width="230px" height="80px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.0" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.0" >  <br>
				</a></div>	  
				<tr><a href="photo.html">
				  <img src="/static/image/icon/ICON3.png" width="230px" height="80px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.0" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.0" >  <br>
				</a></tr>
				<tr><a href="link.html">
				  <img src="/static/image/icon/ICON4.png" width="230px" height="80px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.0" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.0" >  <br>
				</a></tr>

			</table>
		</ul> 
    </div>

    <div class="col-sm-5">

		<div class="slider_container">
		    <div><img src="/static/image/homepage/pic1.jpg" alt="pure css3 slider"></div>
		    <div><img src="/static/image/homepage/pic2.jpg" alt="pure css3 slider"></div>
		    <div><img src="/static/image/homepage/pic3.jpg" alt="pure css3 slider"></div>
		    <div><img src="/static/image/homepage/pic4.jpg" alt="pure css3 slider"></div>	       
		    <div><img src="/static/image/homepage/pic3.jpg" alt="pure css3 slider"></div>
		</div>
		
   	</div>
   
</div>



<audio autoplay>
  <source src="/static/music/Canon.mp3" type="audio/mp3" loop = "true">
</audio>


</body>
</html>

homepage/templates/link.html
<!DOCTYPE html>
<html>
<head>
  <title>其他連結</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
      body {
        background-image: url("image/background.jpg"); 
        background-size: cover;   
    }
    img {
        max-width: 100%;
        height: auto;

    }
    ul#menu {
        padding: 0;
        content: 100;

    }
    /*選單設定*/
     ul { /* 取消ul預設的內縮及樣式 */ 
          margin: 0;
          padding: 0;
          list-style: none;
          
      }

      ul.drop-down-menu {
          display: inline-block;
          font-family: "竹風體";
          font-size: 30px;
      }

      ul.drop-down-menu li {
          position: relative;
          white-space: nowrap;               
      }

      ul.drop-down-menu > li:last-child {
          border-right: none;
      }

      ul.drop-down-menu > li {
          float: left; /* 只有第一層是靠左對齊*/
      }  
      
       ul.drop-down-menu a {
          background-color: transparent;
          color: white;
          display: block;
          padding: 0 30px;
          text-decoration: none;
          line-height: 40px;
          
      }
      ul.drop-down-menu a:hover { /* 滑鼠滑入按鈕變色*/
          background-color:blue; /*#e7e7e7*/
          color: black;
      }
      ul.drop-down-menu li:hover > a { /* 滑鼠移入次選單上層按鈕保持變色*/
          background-color: rgba(60%,60%,60%,0.7);
          color: black;
      }
      ul.drop-down-menu ul {
          border: white 1px solid;
          position: absolute;
          z-index: 99;
          left: -1px;
          top: 100%;
         min-width: 100px;
      }

      ul.drop-down-menu ul li {
          border-bottom: white 1px solid;
      }

      ul.drop-down-menu ul li:last-child {
          border-bottom: none;
      }

        ul.drop-down-menu ul { /*隱藏次選單*/
          display: none;
      } 

      ul.drop-down-menu li:hover > ul { /* 滑鼠滑入展開次選單*/
          display: block;
      }


    /* 嵌入字型設定 */
    @font-face {
        font-family: "竹風體";
        src: url('DFChuStd-W4-BIG.ttf');
    }
    /* 引用嵌入字型 */
    .embFont01 {
        font-family: "竹風體";
        font-size: 36px;
        color:black;
    }
    .embFont02 {
        font-family: "竹風體";
        font-size: 24px;
        color:black;
    }
    /*BOTTON*/
    .botton {
        font-family: "竹風體";
        font-size: 20px;
        color:white;
        background-color: transparent;
        width:160px;height:50px;        

    }
    .button1:hover {background-color: #e7e7e7;color: black;}
    div { font-family: "竹風體", serif; font-size: 30px;}
  </style>

</head>
<body>

<div><img src="image/upper3.png"  ></div> 

<div class="container"> 
  <div style="top:25%;left:23%;position:absolute;">  
  <ul class="drop-down-menu">
        <li><a href="homepage.html">首頁</a></li>
        <li><a href="introduce.html">簡介</a></li>
        <li><a href="newbie.html">新手須知</a>
        <ul>
              <li><a href="buy.html">選購</a>
              </li>
              <li><a href="繁殖.html">繁殖</a>
              </li>
              <li><a href="sun.html">日照與澆水</a>
              </li>
              <li><a href="soil.html">土壤</a>
              </li>
          </ul>
        </li>
        <li><a href="photo.html">圖鑑</a></li>
        <li><a href="link.html">其他連結</a></li>       
  </ul>
  </div>

  <div class="row">
    <div class="col-sm-1">  </div>
    <div class="col-sm-6">  
    <br><h2><b> 相關網站 </b></h2><br>   

      <dl>
        <dt><a href="introduce.html"> ++ 鐵花棧町</a></dt>
        <dt><a href="default.asp"> ++ Saturdays星期六多肉植物 </a></dt>    
        <dt><a href="default.asp"> ++ 蘭花草</a></dt>
        <dt><a href="default.asp"> ++ 一百種常見多肉植物圖鑑 </a></dt>
      </dl>
  
    </div>

    <div class="col-sm-5">

    <div class="slider_container">
        <div><img src="image/新手須知-右邊圖2.png" alt="pure css3 slider"></div>       
    </div>  

    </div>
 </div>
</div>  

</div>  
<img src="image/下灰底2.png" >
</div>


</body>
</html>

plants/templates/plant.html
<!DOCTYPE html>
<html lang="">

<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>多肉植物分類統計</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
/* 嵌入字型設定 
    @font-face {
        font-family: "竹風體";
        src: url("'css/font/DFChuStd-W4-BIG.ttf'%}");
    }*/
    /* 引用嵌入字型 */

  body {
      
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
  th {text-align: center;}
  .margin {margin-bottom: 45px;}

  .bg {
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
 
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }

  </style>
</head>

	<body>
		<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">多肉植物分類統計</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/homepage/">首頁</a></li> 
        <li><a href="/introduce/">簡介</a></li> 
        <li><a href="/newbie/">新手須知</a></li>  
        <li><a href="/link/">相關連結</a></li>      
      </ul>
    </div>
  </div>
</nav>


<!--  Container -->
<div class="container-fluid bg text-center">
  <a href="/photo/" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-search"></span> photo
  </a>

<div class="container-fluid">
	<div class="table-responsive" >   
 	 	<table class="table ">
 	 		<tr>
	 	 		<th>科別</th>
	 	 		<th>名稱</th>
	 	 	</tr>
			{% for kind in kinds %}
			<tr>
				<th>{{kind.name}}  (共 {{ kind.plant_set.all|length }} 種)</th>
				<th> 
				{% for plant in kind.plant_set.all %}				
				{{plant.name}} 、 				
				{% endfor%}
				</th>
			</tr>
			{% endfor%}
		</table>
</div>


</body>
</html>

templates/link.html
<!DOCTYPE HTML>
<!--
	Synchronous by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
{% load staticfiles %}
<html>
	<head>
		<title>Link</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'css/style-desktop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}" >
		
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="{% static 'js/skel.min.js' %}"></script>
		<script src="{% static 'js/skel-panels.min.js' %}"></script>
		<script src="{% static 'js/init.js' %} "></script>
		
		
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
<style>
	#header
	{
		position: relative;
		margin-bottom: 1em 0em;
		text-align: center;
		background: url({% static 'images/upper-w.png' %}) no-repeat center;
		background-size: auto;
	}
	#page {
		padding: 3em 0em;
		background: url({% static 'images/background.jpg' %});   
	    background-size: cover;
	}
	#page2 {
		padding: 0em 0em;
		background: url({% static 'images/background.jpg' %});   
	    background-size: cover;
	}
</style>
	</head>
	<body class="homepage">
		<div id="wrapper">
			
			<!-- Header -->
			<div id="header">
				<div class="container">
					<!-- Nav -->
					<nav id="nav" >
						<ul style = "margin-top:220px" class="drop-down-menu">
					        <li><a href="/homepage/">首頁</a></li>
					        <li><a href="/introduce/">簡介</a></li>
					        <li><a href="/newbie/">新手須知</a></li>
					        <li><a href="/photo/">圖鑑</a></li>
					        <li><a href="/link/">其他連結</a></li>       
						</ul>
						
					</nav>
				</div>
			</div>
			<!-- /Header -->
			
			<div id="page2" >
				<div class="container">
					
						<div class="row">
							<div class="5u -2u ">
								<section id="content" >
									<header style="margin-top: 2em">
										<h2>相關連結</h2>		
										<ul class="style2">
											<li><a href="http://findsucculents.com/"> ++ 鐵花棧町</a></li>
											<li><a href="https://saturdays.takko.me/"> ++ Saturdays星期六多肉植物 </a></li>
											<li><a href="http://tonyorchids.shop2000.com.tw/"> ++ 蘭花草</a></li>
											<li><a href="http://www.buzzhand.com/post_628911.html"> ++ 一百種常見多肉植物圖鑑 </a></li>
										</ul>
									</header>
								</section>
							</div>
							<div class="5u ">
						        <div><img src="{% static 'images/新手須知-右邊圖2.png' %}" style="hight:100%"></div>  
							</div>
						</div>
					
				</div>	
			</div>

			<!-- Footer -->
			
			<div id="footer" >
			
			</div>

			
		</div>
	</body>
</html>

templates/newbie3.html
<!DOCTYPE HTML>
<!--
	Synchronous by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Introduce</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="js/skel.min.js"></script>
		<script src="js/skel-panels.min.js"></script>
		<script src="js/init.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel-noscript.css" />
			<link rel="stylesheet" href="css/style.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->

	</head>
	<body class="homepage">
		<div id="wrapper">
			
			<!-- Header -->
			<div id="header">
				<div class="container">
					<!-- Nav -->
					<nav id="nav" >
						<ul style = "margin-top:220px" class="drop-down-menu">
					        <li><a href="homepage.html">首頁</a></li>
					        <li><a href="introduce.html">簡介</a></li>
					        <li><a href="newbie.html">新手須知</a></li>
					        <li><a href="photo.html">圖鑑</a></li>
					        <li><a href="link.html">其他連結</a></li>       
						</ul>
						
					</nav>
				</div>
			</div>
			<!-- /Header -->
			
			<div id="page2" >
				<div class="container">
					<div class="row">
						<div class="5u -2u skel-cell-important">
							<section id="content" >
								
							<section id="box3">
								<header style="margin-top: 2em">
									<h2>新手需要注意什麼？</h2>		
									<ul style="margin-top: 1em;margin-left: 1em">
										<li ><a href="buy.html">
          <img src="images/newbie/選購Iicon.png" width="210px" height="70px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.1" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.1" ></a></li>
										<li><a href="繁殖.html">
          <img src="images/newbie/繁殖Iicon.png" width="210px" height="70px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.1" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.1" >  <br>
        </a></li>
										<li><a href="sun.html">
          <img src="images/newbie/日照與澆水Iicon.png" width="180px" height="70px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.1" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.1" >  <br>
        </a></li>
										<li><a href="soil.html">
          <img src="images/newbie/土壤Iicon.png" width="210px" height="70px" onMouseOver="this.width=this.width*1.1;this.height=this.height*1.1" onMouseOut="this.width=this.width/1.1;this.height=this.height/1.1" ><br>
        </a></li>
									</ul>
								</header>
							</section>
						</div>
						<div class="5u skel-cell-important">
					        <div><img src="./images/新手須知-右邊圖2.png" style="hight:100%"></div>  
						</div>
					</div>
				</div>	
			</div>

			<!-- Footer -->
			
			<div id="footer" >
			
			</div>

			
		</div>
	</body>
</html>

templates/七福神圖鑑詳細資料.html
<!DOCTYPE HTML>
<!--
	Synchronous by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
{% load static %}
<html>
	<head>
		<title>七福神圖鑑詳細資料</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="{% static 'js/skel.min.js' %}"></script>
		<script src="{% static 'js/skel-panels.min.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>
		
		<link rel="stylesheet" href="{% static 'css/style-desktop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
	</head>
	<style>
	#header
	{
		position: relative;
		margin-bottom: 1em 0em;
		text-align: center;
		background: url({% static 'images/upper-w.png' %}) no-repeat center;
		background-size: auto;
	}

	</style>
	<body class="homepage">
		<div id="wrapper">
			
			<!-- Header -->
			<div id="header">
				<div class="container">
					<!-- Nav -->
					<nav id="nav" >
						<ul style = "margin-top:220px" class="drop-down-menu">
					        <li><a href="/homepage/">首頁</a></li>
					        <li><a href="/introduce/">簡介</a></li>
					        <li><a href="/newbie/">新手須知</a></li>
					        <li><a href="/photo/">圖鑑</a></li>
					        <li><a href="/link/">其他連結</a></li>       
						</ul>
						
					</nav>
				</div>
			</div>
			<!-- /Header -->
			
			
				
					<div><img src="{% static 'images/photo-imfo/七福神圖鑑詳細資料.png' %}"  width="100%"></div>


					
			

			<!-- Footer -->
			
			<div id="footer">
			From Wikipedia
			</div>

			
		</div>
	</body>
</html>